version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manooddy_app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO=${MONGO}
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - manoody-network

  mongo:
    image: mongo:4.4
    container_name: mongodb_manooddy
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - manoody-network

networks:
  manoody-network:
    driver: bridge

volumes:
  mongo-data:
