version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manoody_container
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modulesds
    environment:
      - MYSQL_HOST=my-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=manoodyy1717
      - MYSQL_DATABASE=manoody_db
    depends_on:
      - mysql
    networks:
      - my-app-network

  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=manoodyy1717
      - MYSQL_DATABASE=manoody_db
    ports:
      - '3306:3306'
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge
